#######################################################################
server:
  port: 8080
  context-path: /

logging:
  level: debug

#######################################################################
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/customers?characterEncoding=utf-8
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    password: 123
#    username: root
#    dbcp2:
#       min-idle: 5                         # 数据库连接池的最小维持连接数
#       initial-size: 10                    # 初始化提供的连接数
#       max-total: 10                       # 最大的连接数
#       max-wait-millis: 200                # 等待连接获取的最大超时时间

#######################################################################
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.lzz.pojo

